In [1]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])

In [3]:
assert(a.dtype == np.int64)

In [5]:
a.shape

(3,)

In [25]:
assert(a.shape == (a.size,))

In [28]:
assert(a.shape != (3))

In [29]:
assert(a.shape != 3)

In [30]:
assert(isinstance(a.shape, tuple))

In [31]:
a

array([1, 2, 3])

In [34]:
a.T

array([1, 2, 3])

In [35]:
a.T.shape

(3,)

In [52]:
a = np.zeros(4)
assert (a == np.array([0, 0, 0, 0])).all()

In [41]:
all([True, False])

False

In [42]:
all([True, True])

True

In [53]:
assert isinstance(a.shape, tuple)

In [64]:
a = np.array([[0.12, 0.45, 0.78, 1.34, 2.91], [0.21, 0.54, 0.78, 1.43, 2.19]])

In [65]:
a

array([[0.12, 0.45, 0.78, 1.34, 2.91],
       [0.21, 0.54, 0.78, 1.43, 2.19]])

In [59]:
a.shape

(2, 5)

In [60]:
assert(a.shape == (2, 5))

In [63]:
assert(a.ndim == 2)

In [68]:
a = np.random.rand(3, 3, 4)
a

array([[[0.44084947, 0.24251498, 0.77022093, 0.20813781],
        [0.3531438 , 0.50395597, 0.96409215, 0.51015095],
        [0.80258366, 0.19463104, 0.15220298, 0.94671396]],

       [[0.81952391, 0.48318202, 0.3696767 , 0.47835388],
        [0.19815026, 0.10386067, 0.75396159, 0.85740158],
        [0.84181578, 0.01469915, 0.16274221, 0.40724949]],

       [[0.64221872, 0.41207734, 0.77596246, 0.7514986 ],
        [0.81139215, 0.58713222, 0.75739015, 0.59995078],
        [0.72113774, 0.37824504, 0.4644048 , 0.16211452]]])

In [69]:
assert(a.shape == (3, 3, 4))

In [70]:
assert(a.ndim == 3)

In [72]:
a = np.array(np.arange(1, 25, 1, np.int8))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int8)

In [73]:
assert(a == [x for x in range(1, 25)]).all()

In [74]:
b = a.reshape(2, 12)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int8)

In [76]:
assert(b.size == 24)

In [77]:
assert(b.shape == (2, 12))

In [78]:
assert(len(b) == 2)

In [79]:
assert(b.ndim == 2)